### ISSUE TITLE
Dependency on `curses`

### ISSUE THREAD

**Issue by LiaungYip** [khardix/mccurse#1]
`mccurse` uses the `curses` library (name co-incidental), which doesn't come with Python for Windows out-of-the-box.

	PS C:\Users\lws\mccurse\Scripts> .\mccurse.exe
	Traceback (most recent call last):
	  File "c:\program files\python35\Lib\runpy.py", line 184, in _run_module_as_main
	    "__main__", mod_spec)
	  File "c:\program files\python35\Lib\runpy.py", line 85, in _run_code
	    exec(code, run_globals)
	  File "C:\Users\lws\mccurse\Scripts\mccurse.exe\__main__.py", line 5, in <module>
	  File "c:\users\lws\mccurse\lib\site-packages\mccurse\cli.py", line 3, in <module>
	    import curses
	  File "c:\program files\python35\Lib\curses\__init__.py", line 13, in <module>
	    from _curses import *
	ImportError: No module named '_curses'

[Installing a binary version of `curses` via a wheel package](https://stackoverflow.com/questions/32417379/what-is-needed-for-curses-in-python-3-4-on-windows7) lets you run `mccurses` on Windows.

It may help to add this to the project README, to assist future (confused) Windows users.

**Comment by khardix** [comment]
Thanks for the heads-up. Unfortunately, I do not have access to a Windows test environment, and so any modifications from my side would be a guesswork with no way of telling if it actually works. If you could submit a PR with the proposed README changes, I would greatly appreciate it.
