### ISSUE TITLE
All commands fail with `TypeError: unhashable type: 'Database'`

### ISSUE THREAD

**Issue by LiaungYip** [khardix/mccurse#2]
Python 3.5.2 on Windows 10 64-bit.

Create a new `virtualenv`:

	PS C:\Users\lws> virtualenv mccurse
	Using base prefix 'c:\\program files\\python35'
	New python executable in C:\Users\lws\mccurse\Scripts\python.exe
	Installing setuptools, pip, wheel...done.

Check Python version:

	PS C:\Users\lws\mccurse\Scripts> python
	Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
	Type "help", "copyright", "credits" or "license" for more information.
	>>>

Install `mccurse` from PyPI:

	PS C:\Users\lws\mccurse\Scripts> ./pip install mccurse --verbose

Install `curses` from a binary wheel (refer #1)

	PS C:\Users\lws\mccurse\Scripts> ./pip install C:\Users\lws\Downloads\curses-2.2-cp35-none-win_amd64.whl

Run `mccurse` - succeeds - shows help text

	PS C:\Users\lws\mccurse\Scripts> .\mccurse.exe
	Usage: mccurse [OPTIONS] COMMAND [ARGS]...

	  Unofficial CLI client for Minecraft Curse Forge.

	Options:
	  --version    Show the version and exit.
	  --refresh    Force refresh of existing mods list.
	  -q, --quiet  Silence the process reporting.
	  --help       Show this message and exit.

	Commands:
	  auth     Authenticate user for subsequent file...
	  install  Install new MOD into a mod-pack.
	  new      Create and initialize a new mod-pack.
	  remove   Remove a MOD from a mod-pack.
	  search   Search Curse Forge for a mod named NAME.
	  upgrade  Upgrade MOD and its dependencies.

Run any command, i.e. `mccurse auth` - fails.

	PS C:\Users\lws\mccurse\Scripts> .\mccurse.exe auth
	Traceback (most recent call last):
	  File "c:\program files\python35\Lib\runpy.py", line 184, in _run_module_as_main
	    "__main__", mod_spec)
	  File "c:\program files\python35\Lib\runpy.py", line 85, in _run_code
	    exec(code, run_globals)
	  File "C:\Users\lws\mccurse\Scripts\mccurse.exe\__main__.py", line 9, in <module>
	  File "c:\users\lws\mccurse\lib\site-packages\click\core.py", line 722, in __call__
	    return self.main(*args, **kwargs)
	  File "c:\users\lws\mccurse\lib\site-packages\click\core.py", line 697, in main
	    rv = self.invoke(ctx)
	  File "c:\users\lws\mccurse\lib\site-packages\click\core.py", line 1063, in invoke
	    Command.invoke(self, ctx)
	  File "c:\users\lws\mccurse\lib\site-packages\click\core.py", line 895, in invoke
	    return ctx.invoke(self.callback, **ctx.params)
	  File "c:\users\lws\mccurse\lib\site-packages\click\core.py", line 535, in invoke
	    return callback(*args, **kwargs)
	  File "c:\users\lws\mccurse\lib\site-packages\click\decorators.py", line 17, in new_func
	    return f(get_current_context(), *args, **kwargs)
	  File "c:\users\lws\mccurse\lib\site-packages\mccurse\cli.py", line 63, in cli
	    'default_game': Game.find('Minecraft'),  # Default game to query and use
	  File "c:\users\lws\mccurse\lib\site-packages\mccurse\curse.py", line 291, in find
	    return cls(name=name.capitalize(), **defaults)
	  File "c:\users\lws\mccurse\lib\site-packages\mccurse\curse.py", line 265, in __init__
	    if self.database.version == epoch:
	  File "c:\users\lws\mccurse\lib\site-packages\mccurse\curse.py", line 192, in version
	    timestamp, = self.engine.execute('PRAGMA user_version').first()
	TypeError: unhashable type: 'Database'

**Comment by khardix** [comment]
Thanks for the report(s). I will try to look into it shortly.

**Comment by khardix** [comment]
I think I found the culprit – [attrs](https://attrs.readthedocs.io/en/stable/index.html) in current version has different default and semantics for the `hash` decorator attribute.

More than anything, this is bug in the packaging process -- specifically, the `install_requires` section of `setup.py` should restrict the dependencies to tested (major) versions.

However, the decorator(s) of the `Database` and other classes should be also changed to reflect the new semantics.
